-- ============================================================================
-- Inaaya Commerce Platform - database bootstrap, step 2 of 3: the core schema
--
-- One account per person across the whole platform. Before the integration the
-- warehouse and the courier portal each had a `users` table with its own admin
-- and its own password; signing in to one said nothing to the other. Now both
-- read this table and both accept the same signed session token.
-- ============================================================================

\set ON_ERROR_STOP on

-- -------------------------------------------------------------------- users

CREATE TABLE IF NOT EXISTS core.users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Stored lower case by both applications; citext makes the lookup and the
  -- unique constraint case-insensitive regardless.
  username      citext       NOT NULL,
  full_name     varchar(128) NOT NULL,
  -- "+60 1XXXXXXXX", normalised by the courier portal. Optional.
  phone         varchar(32)  NULL,
  email         citext       NULL,
  -- Either "pbkdf2_sha256$<iterations>$<salt>$<hash>" (new and courier
  -- accounts) or a bcrypt "$2a$..." hash (accounts migrated from the
  -- warehouse). Both applications verify both, and rehash to PBKDF2 on login.
  password_hash varchar(255) NOT NULL,
  --   admin     everything, both modules
  --   operator  warehouse floor (intake, picking, returns, finding) and shipping
  --   merchant  the courier merchant portal only
  role          varchar(16)  NOT NULL DEFAULT 'operator',
  --   active    can sign in
  --   pending   signed up on the courier portal, waiting for an admin
  --   blocked   switched off; every session is revoked
  status        varchar(16)  NOT NULL DEFAULT 'active',
  -- The warehouse API and the handheld read a numeric flag. Derived, so the two
  -- can never disagree.
  active        smallint     GENERATED ALWAYS AS (CASE WHEN status = 'active' THEN 1 ELSE 0 END) STORED,
  last_login_at timestamptz  NULL,
  created_at    timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT ck_users_role   CHECK (role IN ('admin', 'operator', 'merchant')),
  CONSTRAINT ck_users_status CHECK (status IN ('active', 'pending', 'blocked'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_phone ON core.users (phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON core.users (email) WHERE email IS NOT NULL;

COMMENT ON TABLE core.users IS 'One account per person for the whole platform';

-- ----------------------------------------------------------------- sessions

-- A sign-in. The browser or handheld holds a JWT whose `sid` claim is this
-- row's id; both APIs check the row on every request, which is what makes
-- "sign out" and "block this account" take effect immediately instead of when
-- the token happens to expire.
CREATE TABLE IF NOT EXISTS core.user_sessions (
  id           uuid         PRIMARY KEY,
  user_id      integer      NOT NULL REFERENCES core.users (id) ON DELETE CASCADE,
  -- web | handheld | api - shown to an admin, and used to pick a lifetime
  client       varchar(16)  NOT NULL DEFAULT 'web',
  created_at   timestamptz  NOT NULL DEFAULT now(),
  expires_at   timestamptz  NOT NULL,
  last_seen_at timestamptz  NULL,
  revoked_at   timestamptz  NULL,
  ip           varchar(64)  NULL,
  user_agent   varchar(256) NULL
);

CREATE INDEX IF NOT EXISTS ix_user_sessions_user    ON core.user_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_user_sessions_expires ON core.user_sessions (expires_at);

-- An ended sign-in is announced on the channel core_session_ended, with the
-- session id. The warehouse API remembers a live session for a few seconds (a
-- handheld scans many tags a minute) and listens here, so signing out or
-- blocking an account on the courier portal reaches the dashboard at once.
-- Both APIs end a session by deleting its row; setting revoked_at is announced
-- too, for anything that prefers to keep the row.
CREATE OR REPLACE FUNCTION core.announce_session_end() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM pg_notify('core_session_ended', OLD.id::text);
  ELSIF NEW.revoked_at IS NOT NULL AND OLD.revoked_at IS NULL THEN
    PERFORM pg_notify('core_session_ended', NEW.id::text);
  END IF;
  RETURN NULL;
END;
$$;

CREATE OR REPLACE TRIGGER trg_user_sessions_announce_end
  AFTER DELETE OR UPDATE OF revoked_at ON core.user_sessions
  FOR EACH ROW EXECUTE FUNCTION core.announce_session_end();

-- --------------------------------------------------------------- audit log

-- Append-only record of security-relevant and cross-module events: sign-ins,
-- account changes, courier bookings. Nothing updates or deletes a row.
CREATE TABLE IF NOT EXISTS core.audit_log (
  id             bigint       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  occurred_at    timestamptz  NOT NULL DEFAULT now(),
  module         varchar(16)  NOT NULL,            -- core | warehouse | courier
  action         varchar(64)  NOT NULL,            -- e.g. auth.login, courier.booked
  outcome        varchar(16)  NOT NULL DEFAULT 'success',
  actor_user_id  integer      NULL REFERENCES core.users (id) ON DELETE SET NULL,
  actor_username citext       NULL,
  entity         varchar(64)  NULL,
  entity_id      varchar(64)  NULL,
  detail         jsonb        NULL,
  ip             varchar(64)  NULL
);

CREATE INDEX IF NOT EXISTS ix_audit_log_when   ON core.audit_log (occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_log_actor  ON core.audit_log (actor_user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_log_entity ON core.audit_log (entity, entity_id);

-- -------------------------------------------------------- default accounts

-- The two accounts a new platform starts with - only while there are no
-- accounts at all, so a changed password is never put back. Passwords come from
-- PLATFORM_ADMIN_PASSWORD / PLATFORM_MERCHANT_PASSWORD; change them after the
-- first login.
INSERT INTO core.users (username, full_name, phone, password_hash, role, status)
SELECT seed.username, seed.full_name, seed.phone,
       public.crypt(seed.password, public.gen_salt('bf', 10)), seed.role, 'active'
  FROM (VALUES
          ('admin',  'Administrator',                NULL,            :'admin_password',    'admin'),
          ('linked', 'LINKED INTERNATIONAL SDN BHD', '+60 135763706', :'merchant_password', 'merchant')
       ) AS seed (username, full_name, phone, password, role)
 WHERE NOT EXISTS (SELECT 1 FROM core.users);

-- ------------------------------------------------------------------- grants

GRANT USAGE ON SCHEMA core TO warehouse_app, courier_app;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON core.users, core.user_sessions TO warehouse_app, courier_app;
GRANT SELECT, INSERT ON core.audit_log TO warehouse_app, courier_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA core TO warehouse_app, courier_app;
