-- Clothing warehouse schema (PostgreSQL 16, schema `warehouse`).
--
-- Applied on every start, not just the first: every statement is idempotent, so
-- a deploy that lands on an older database brings it up to date without anybody
-- running a migration by hand. Columns added after the first release are
-- written as ADD COLUMN IF NOT EXISTS at the bottom, next to the table.
--
-- Ported from MySQL 8 when the warehouse and the J&T courier portal became one
-- platform on one database. The shape of every table is unchanged; the types
-- are PostgreSQL's:
--
--   ENUM(...)        varchar + CHECK       - a new value is one line, not a table rebuild
--   TINYINT(1)       smallint              - the handheld reads these as numbers
--   DATETIME         timestamptz           - stored in UTC, shown in local time
--   VARBINARY        bytea
--   users            core.users            - one account across the platform
--
-- Four decisions that are not obvious from the DDL:
--
--  * A tag's EPC is whatever the factory printed on it. We do not encode
--    meaning into it and we never write to a tag. `items.epc` is therefore an
--    opaque unique key, and everything you want to know about a garment is
--    reached by joining, not by decoding. This is why any brand of tag works.
--
--  * `movements` is append-only. `items.room_id` and `items.status` are
--    denormalised for fast queries, but the ledger is the record of truth and
--    is what a disputed return gets settled with. Never UPDATE or DELETE a row.
--
--  * `order_items` is the EPC-to-order binding. It is the whole point of the
--    return check: a customer returning something must return the physical unit
--    that was actually sent, and this table is the only place that is recorded.
--
--  * Dropship products never have rows in `items`. They have no tag, never
--    enter a room, and their stock is a number on the variant rather than a
--    pile of garments. Any query that counts physical stock must exclude them.

-- ------------------------------------------------------------------- rooms

-- Where a garment physically is: A1, B2, C3. `kind` separates a shelf you can
-- pick from out of the staging areas, so "what is sellable" does not
-- accidentally include the returns bench.
CREATE TABLE IF NOT EXISTS warehouse.rooms (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        varchar(32)  NOT NULL UNIQUE,
  name        varchar(128) NOT NULL,
  kind        varchar(16)  NOT NULL DEFAULT 'storage'
                CHECK (kind IN ('storage','receiving','packing','returns','quarantine')),
  capacity    integer      NULL,
  notes       text         NULL,
  active      smallint     NOT NULL DEFAULT 1,
  created_at  timestamptz  NOT NULL DEFAULT now()
);

-- A tag stuck on the door. The handheld scans it and knows where it is standing
-- instead of the operator picking a room off a list and picking the wrong one.
CREATE TABLE IF NOT EXISTS warehouse.room_tags (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id    integer      NOT NULL REFERENCES warehouse.rooms (id),
  epc        varchar(64)  NOT NULL UNIQUE,
  label      varchar(128) NULL,
  active     smallint     NOT NULL DEFAULT 1,
  created_at timestamptz  NOT NULL DEFAULT now()
);

-- -------------------------------------------------------- catalogue lookups

CREATE TABLE IF NOT EXISTS warehouse.categories (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       varchar(32)  NOT NULL UNIQUE,
  name       varchar(128) NOT NULL,
  active     smallint     NOT NULL DEFAULT 1,
  created_at timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS warehouse.colors (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       varchar(32)  NOT NULL UNIQUE,
  name       varchar(64)  NOT NULL,
  -- Drawn as a swatch in the dashboard so a picker shows the colour rather
  -- than the word for it.
  hex        varchar(7)   NULL,
  active     smallint     NOT NULL DEFAULT 1,
  created_at timestamptz  NOT NULL DEFAULT now()
);

-- `sort_order` exists because sizes do not sort alphabetically: S, M, L, XL
-- comes out as L, M, S, XL, and a size list in that order is unusable.
CREATE TABLE IF NOT EXISTS warehouse.sizes (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       varchar(32)  NOT NULL UNIQUE,
  name       varchar(64)  NOT NULL,
  sort_order integer      NOT NULL DEFAULT 0,
  active     smallint     NOT NULL DEFAULT 1,
  created_at timestamptz  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- products

-- The style: "Embroidered Shalwar Kameez". Not sellable on its own; you sell a
-- colour and a size of it, which is a variant.
CREATE TABLE IF NOT EXISTS warehouse.products (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku         varchar(64)   NOT NULL UNIQUE,
  name        varchar(200)  NOT NULL,
  category_id integer       NOT NULL REFERENCES warehouse.categories (id),
  description text          NULL,
  -- 'stock' is tagged and sits in a room. 'dropship' never arrives: the
  -- supplier ships it to the customer, so it has no tag and no room.
  stock_type  varchar(16)   NOT NULL DEFAULT 'stock' CHECK (stock_type IN ('stock','dropship')),
  supplier    varchar(200)  NULL,
  cost_price  numeric(12,2) NOT NULL DEFAULT 0,
  sale_price  numeric(12,2) NOT NULL DEFAULT 0,
  active      smallint      NOT NULL DEFAULT 1,
  created_at  timestamptz   NOT NULL DEFAULT now(),
  -- Kept current by the trigger below (MySQL's ON UPDATE CURRENT_TIMESTAMP).
  updated_at  timestamptz   NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION warehouse.touch_updated_at() RETURNS trigger
  LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_products_updated_at ON warehouse.products;
CREATE TRIGGER trg_products_updated_at
  BEFORE UPDATE ON warehouse.products
  FOR EACH ROW EXECUTE FUNCTION warehouse.touch_updated_at();

-- The photos of a product, in the order they are shown. The lowest sort_order
-- is the cover: the one on a search result and on the handheld.
--
-- Only the file name is stored. The file itself lives in the uploads folder,
-- outside wwwroot, because building the dashboard empties wwwroot and would
-- take every photo with it.
CREATE TABLE IF NOT EXISTS warehouse.product_photos (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  integer      NOT NULL REFERENCES warehouse.products (id) ON DELETE CASCADE,
  file_name   varchar(80)  NOT NULL UNIQUE,
  sort_order  integer      NOT NULL DEFAULT 0,
  -- Search by photo: what the recognition model saw in this photo, and which model.
  embedding       bytea       NULL,
  embedding_model varchar(40) NULL,
  created_at  timestamptz  NOT NULL DEFAULT now()
);

-- One colour and size of a product. This is the thing an order line points at.
--
-- The two price columns are nullable overrides: NULL means "whatever the
-- product says", so putting the price up on a style is one edit rather than
-- forty. `dropship_qty` is only meaningful when the product is dropship, and is
-- what the supplier says they can supply.
CREATE TABLE IF NOT EXISTS warehouse.variants (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    integer       NOT NULL REFERENCES warehouse.products (id) ON DELETE CASCADE,
  color_id      integer       NOT NULL REFERENCES warehouse.colors (id),
  size_id       integer       NOT NULL REFERENCES warehouse.sizes (id),
  sku           varchar(80)   NOT NULL UNIQUE,
  cost_price    numeric(12,2) NULL,
  sale_price    numeric(12,2) NULL,
  dropship_qty  integer       NOT NULL DEFAULT 0,
  -- Warn when fewer than this are on the shelves. 0 turns the warning off.
  -- 10 by default: the warehouse wants to be told when a colour and size is
  -- down to fewer than ten.
  reorder_level integer       NOT NULL DEFAULT 10,
  active        smallint      NOT NULL DEFAULT 1,
  created_at    timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT uq_variant UNIQUE (product_id, color_id, size_id)
);

-- ----------------------------------------------------------------- batches

-- An intake. "50 shalwar kameez arrived" is one batch; the colours and sizes
-- inside it are its lines.
CREATE TABLE IF NOT EXISTS warehouse.batches (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_no     varchar(40)  NOT NULL UNIQUE,
  supplier     varchar(200) NULL,
  room_id      integer      NULL REFERENCES warehouse.rooms (id),
  status       varchar(16)  NOT NULL DEFAULT 'open' CHECK (status IN ('open','complete','cancelled')),
  notes        text         NULL,
  created_by   integer      NULL REFERENCES core.users (id) ON DELETE SET NULL,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  completed_at timestamptz  NULL
);

-- `quantity` is how many tags the handheld will accept against this line. It is
-- the whole of the "I will give you 50 EPCs" contract: the 51st scan is
-- refused, which is what stops a mis-scan quietly inventing stock.
CREATE TABLE IF NOT EXISTS warehouse.batch_lines (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id   integer       NOT NULL REFERENCES warehouse.batches (id) ON DELETE CASCADE,
  variant_id integer       NOT NULL REFERENCES warehouse.variants (id),
  quantity   integer       NOT NULL CHECK (quantity > 0),
  unit_cost  numeric(12,2) NOT NULL DEFAULT 0
);

-- ------------------------------------------------------------------- items

-- One physical garment, one tag. Stock products only.
--
-- `cost_price` is copied off the batch line rather than joined to it, because
-- inventory value has to stay true to what this unit actually cost.
CREATE TABLE IF NOT EXISTS warehouse.items (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  epc           varchar(64)   NOT NULL UNIQUE,
  tid           varchar(64)   NULL,
  variant_id    integer       NOT NULL REFERENCES warehouse.variants (id),
  batch_line_id integer       NULL REFERENCES warehouse.batch_lines (id) ON DELETE SET NULL,
  room_id       integer       NULL REFERENCES warehouse.rooms (id) ON DELETE SET NULL,
  status        varchar(16)   NOT NULL DEFAULT 'in_stock'
                  CHECK (status IN ('in_stock','allocated','shipped','returned','damaged','lost','written_off')),
  cost_price    numeric(12,2) NOT NULL DEFAULT 0,
  notes         text          NULL,
  enrolled_at   timestamptz   NOT NULL DEFAULT now(),
  enrolled_by   integer       NULL REFERENCES core.users (id) ON DELETE SET NULL,
  last_seen_at  timestamptz   NULL
);

-- ------------------------------------------------------------------ orders

CREATE TABLE IF NOT EXISTS warehouse.orders (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no       varchar(40)   NOT NULL UNIQUE,
  -- What the customer is told to quote. Counted from 1 rather than derived
  -- from the date, because it is read out over a phone.
  tracking_id    integer       NULL UNIQUE,
  customer_name  varchar(200)  NOT NULL,
  customer_phone varchar(64)   NULL,
  customer_email varchar(200)  NULL,
  address        text          NULL,
  city           varchar(128)  NULL,
  -- Kept as text: leading zeros are real, and nothing is calculated from it.
  postal_code    varchar(16)   NULL,
  -- 'manual' is somebody typing it in here. 'web' is reserved for the public site.
  channel        varchar(16)   NOT NULL DEFAULT 'manual' CHECK (channel IN ('manual','web')),
  -- Whether the money is already in. 'cod' is the default because it is the
  -- one that still owes something.
  payment_type   varchar(8)    NOT NULL DEFAULT 'cod' CHECK (payment_type IN ('paid','cod')),
  status         varchar(20)   NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','allocated','packed','shipped','delivered',
                                     'cancelled','returned','partly_returned')),
  subtotal       numeric(12,2) NOT NULL DEFAULT 0,
  shipping_fee   numeric(12,2) NOT NULL DEFAULT 0,
  discount       numeric(12,2) NOT NULL DEFAULT 0,
  total          numeric(12,2) NOT NULL DEFAULT 0,
  refunded_total numeric(12,2) NOT NULL DEFAULT 0,
  notes          text          NULL,
  created_by     integer       NULL REFERENCES core.users (id) ON DELETE SET NULL,
  placed_at      timestamptz   NOT NULL DEFAULT now(),
  shipped_at     timestamptz   NULL,
  delivered_at   timestamptz   NULL
);

CREATE TABLE IF NOT EXISTS warehouse.order_lines (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   integer       NOT NULL REFERENCES warehouse.orders (id) ON DELETE CASCADE,
  variant_id integer       NOT NULL REFERENCES warehouse.variants (id),
  quantity   integer       NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL DEFAULT 0,
  -- Copied from the product at the moment of ordering, so a product switched
  -- to dropship later does not rewrite how an old order was fulfilled.
  route      varchar(16)   NOT NULL DEFAULT 'stock' CHECK (route IN ('stock','dropship'))
);

-- Which physical garment went out against which line. `epc` is duplicated from
-- the item on purpose: the return check must keep working even if the item row
-- is later re-tagged or written off.
CREATE TABLE IF NOT EXISTS warehouse.order_items (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      integer     NOT NULL REFERENCES warehouse.orders (id) ON DELETE CASCADE,
  order_line_id integer     NOT NULL REFERENCES warehouse.order_lines (id) ON DELETE CASCADE,
  item_id       integer     NOT NULL REFERENCES warehouse.items (id),
  epc           varchar(64) NOT NULL,
  status        varchar(16) NOT NULL DEFAULT 'allocated' CHECK (status IN ('allocated','shipped','returned')),
  picked_at     timestamptz NOT NULL DEFAULT now(),
  picked_by     integer     NULL REFERENCES core.users (id) ON DELETE SET NULL,
  -- One garment cannot be on the same order twice.
  CONSTRAINT uq_order_item UNIQUE (order_id, item_id)
);

-- ----------------------------------------------------------------- returns

CREATE TABLE IF NOT EXISTS warehouse.returns (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_no     varchar(40)   NOT NULL UNIQUE,
  order_id      integer       NOT NULL REFERENCES warehouse.orders (id),
  status        varchar(16)   NOT NULL DEFAULT 'requested'
                  CHECK (status IN ('requested','received','closed','rejected','cancelled')),
  reason        text          NULL,
  refund_amount numeric(12,2) NOT NULL DEFAULT 0,
  notes         text          NULL,
  requested_at  timestamptz   NOT NULL DEFAULT now(),
  received_at   timestamptz   NULL,
  received_by   integer       NULL REFERENCES core.users (id) ON DELETE SET NULL
);

-- One garment coming back, and the verdict on it. Every failing case is kept
-- rather than rejected at the door: a tag that belongs to a different order is a
-- fact worth having on the record. `item_id` is null when the tag is not ours.
CREATE TABLE IF NOT EXISTS warehouse.return_lines (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id       integer       NOT NULL REFERENCES warehouse.returns (id) ON DELETE CASCADE,
  order_item_id   integer       NULL REFERENCES warehouse.order_items (id) ON DELETE SET NULL,
  item_id         integer       NULL REFERENCES warehouse.items (id) ON DELETE SET NULL,
  epc             varchar(64)   NOT NULL,
  verdict         varchar(16)   NOT NULL DEFAULT 'pending'
                    CHECK (verdict IN ('pending','matched','wrong_order','not_shipped','unknown_tag')),
  item_condition  varchar(16)   NOT NULL DEFAULT 'resellable' CHECK (item_condition IN ('resellable','damaged')),
  -- How much use is left in the garment, decided at the counter:
  --   1  no defects, goes straight back into stock
  --   2  defective but still usable, kept and marked damaged
  --   3  defective beyond use, written off
  reusability     smallint      NOT NULL DEFAULT 1,
  restock_room_id integer       NULL REFERENCES warehouse.rooms (id) ON DELETE SET NULL,
  refund_amount   numeric(12,2) NOT NULL DEFAULT 0,
  received_at     timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT uq_return_line UNIQUE (return_id, epc)
);

-- --------------------------------------------------------------- movements

-- Append-only. One row per thing that happened to one garment.
CREATE TABLE IF NOT EXISTS warehouse.movements (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id      integer     NOT NULL REFERENCES warehouse.items (id),
  type         varchar(16) NOT NULL
                 CHECK (type IN ('intake','move','allocate','ship','return','restock','adjust','write_off')),
  from_room_id integer     NULL REFERENCES warehouse.rooms (id) ON DELETE SET NULL,
  to_room_id   integer     NULL REFERENCES warehouse.rooms (id) ON DELETE SET NULL,
  from_status  varchar(32) NULL,
  to_status    varchar(32) NULL,
  order_id     integer     NULL REFERENCES warehouse.orders (id) ON DELETE SET NULL,
  return_id    integer     NULL REFERENCES warehouse.returns (id) ON DELETE SET NULL,
  user_id      integer     NULL REFERENCES core.users (id) ON DELETE SET NULL,
  note         text        NULL,
  occurred_at  timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------- find requests

-- The radar list. The office puts a garment on here; every handheld picks it up
-- and the reader turns into a hot-and-cold finder for it.
CREATE TABLE IF NOT EXISTS warehouse.find_requests (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  epc           varchar(64) NOT NULL,
  item_id       integer     NULL REFERENCES warehouse.items (id) ON DELETE SET NULL,
  status        varchar(16) NOT NULL DEFAULT 'open' CHECK (status IN ('open','found','cancelled')),
  note          text        NULL,
  created_by    integer     NULL REFERENCES core.users (id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  found_at      timestamptz NULL,
  found_by      integer     NULL REFERENCES core.users (id) ON DELETE SET NULL,
  found_room_id integer     NULL REFERENCES warehouse.rooms (id) ON DELETE SET NULL,
  -- Set when several garments were put on the list as one request: "find any
  -- navy medium". Finding one of them closes the rest.
  group_key     varchar(40) NULL
);

-- --------------------------------------------------------------- shipments

-- A parcel booked with the courier for an order: the join between the two
-- modules. The warehouse owns this row; the courier owns the parcel itself
-- (courier.orders), and the two meet on the tracking number, which both sides
-- treat as the parcel's identity. `status` is the last tracking status the
-- courier sync saw, so an order list does not have to reach into another module
-- for every row.
CREATE TABLE IF NOT EXISTS warehouse.shipments (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       integer       NOT NULL REFERENCES warehouse.orders (id) ON DELETE CASCADE,
  carrier        varchar(32)   NOT NULL DEFAULT 'J&T Express',
  tracking_no    varchar(32)   NOT NULL UNIQUE,
  status         varchar(16)   NOT NULL DEFAULT 'CREATED',
  sortation_code varchar(24)   NULL,
  route_code     varchar(8)    NULL,
  weight_kg      numeric(8,2)  NULL,
  freight_fee    numeric(10,2) NULL,
  cod_amount     numeric(12,2) NOT NULL DEFAULT 0,
  booked_by      integer       NULL REFERENCES core.users (id) ON DELETE SET NULL,
  booked_at      timestamptz   NOT NULL DEFAULT now(),
  status_at      timestamptz   NULL,
  synced_at      timestamptz   NULL
);

-- ----------------------------------------------------------------- indexes

CREATE INDEX IF NOT EXISTS idx_room_tags_room            ON warehouse.room_tags (room_id);
CREATE INDEX IF NOT EXISTS idx_products_category         ON warehouse.products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_type             ON warehouse.products (stock_type);
CREATE INDEX IF NOT EXISTS idx_products_name_lower       ON warehouse.products (lower(name));
CREATE INDEX IF NOT EXISTS idx_variants_product          ON warehouse.variants (product_id);
CREATE INDEX IF NOT EXISTS idx_batches_status            ON warehouse.batches (status);
CREATE INDEX IF NOT EXISTS idx_batch_lines_batch         ON warehouse.batch_lines (batch_id);
CREATE INDEX IF NOT EXISTS idx_batch_lines_variant       ON warehouse.batch_lines (variant_id);
CREATE INDEX IF NOT EXISTS idx_items_variant             ON warehouse.items (variant_id);
CREATE INDEX IF NOT EXISTS idx_items_room                ON warehouse.items (room_id);
CREATE INDEX IF NOT EXISTS idx_items_status              ON warehouse.items (status);
CREATE INDEX IF NOT EXISTS idx_items_line                ON warehouse.items (batch_line_id);
CREATE INDEX IF NOT EXISTS idx_orders_status             ON warehouse.orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_placed             ON warehouse.orders (placed_at);
CREATE INDEX IF NOT EXISTS idx_order_lines_order         ON warehouse.order_lines (order_id);
CREATE INDEX IF NOT EXISTS idx_order_lines_variant       ON warehouse.order_lines (variant_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order         ON warehouse.order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_line          ON warehouse.order_items (order_line_id);
CREATE INDEX IF NOT EXISTS idx_order_items_item          ON warehouse.order_items (item_id);
CREATE INDEX IF NOT EXISTS idx_order_items_epc           ON warehouse.order_items (epc);
CREATE INDEX IF NOT EXISTS idx_returns_order             ON warehouse.returns (order_id);
CREATE INDEX IF NOT EXISTS idx_returns_status            ON warehouse.returns (status);
CREATE INDEX IF NOT EXISTS idx_return_lines_ret          ON warehouse.return_lines (return_id);
CREATE INDEX IF NOT EXISTS idx_return_lines_epc          ON warehouse.return_lines (epc);
CREATE INDEX IF NOT EXISTS idx_movements_item            ON warehouse.movements (item_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_movements_when            ON warehouse.movements (occurred_at);
CREATE INDEX IF NOT EXISTS idx_movements_order           ON warehouse.movements (order_id);
CREATE INDEX IF NOT EXISTS idx_find_status               ON warehouse.find_requests (status);
CREATE INDEX IF NOT EXISTS idx_find_epc                  ON warehouse.find_requests (epc);
CREATE INDEX IF NOT EXISTS idx_find_group                ON warehouse.find_requests (group_key);
CREATE INDEX IF NOT EXISTS idx_product_photos_product    ON warehouse.product_photos (product_id, sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS uq_shipments_order     ON warehouse.shipments (order_id);
CREATE INDEX IF NOT EXISTS idx_shipments_status          ON warehouse.shipments (status);
